var aero = {
    "AAX	SBAX	Romeu Zema Airport	Araxa":null,
"AIR	SWRP	Aripuanã Airport	Aripuana":null,
"APQ	SNAL	Arapiraca Airport	Arapiraca":null,
"ARU	SBAU	Araçatuba Airport	Aracatuba":null,
"AUX	SWGN	Araguaína Airport	Araguaina":null,
"BAU	SBBU	Bauru Airport	Bauru":null,
"BEL	SBBE	Val de Cans/Júlio Cezar Ribeiro International Airport	Belem":null,
"BGX	SBBG	Comandante Gustavo Kraemer Airport	Bage":null,
"BNU	SSBL	Blumenau Airport	BLUMENAU":null,
"BRA	SNBR	Barreiras Airport	Barreiras":null,
"BVB	SBBV	Atlas Brasil Cantanhede Airport	Boa Vista":null,
"BVS	SNVS	Breves Airport	Breves":null,
"BZC	SBBZ	Umberto Modiano Airport	Buzios":null,
"CAF	SWCA	Carauari Airport	Carauari":null,
"CAW	SBCP	Bartolomeu Lisandro Airport	Campos":null,
"CCM	SBCM	Diomício Freitas Airport	Criciuma":null,
"CDJ	SBAA	Conceição do Araguaia Airport	Conceicao Do Araguaia":null,
"CFC	SBCD	Caçador Airport	Cacador":null,
"CGB	SBCY	Marechal Rondon Airport	Cuiaba":null,
"CGR	SBCG	Campo Grande Airport	Campo Grande":null,
"CKS	SBCJ	Carajás Airport	Parauapebas":null,
"CLV	SBCN	Nelson Ribeiro Guimarães Airport	Caldas Novas":null,
"CMP	SNKE	Santana do Araguaia Airport	Santana do Araguaia":null,
"CPQ	SDAM	Amarais Airport	Campinas":null,
"CRQ	SBCV	Caravelas Airport	Caravelas":null,
"CXJ	SBCX	Hugo Cantergiani Regional Airport	Caxias Do Sul":null,
"DIQ	SNDV	Brigadeiro Cabral Airport	Divinopolis":null,
"DOU	SSDO	Dourados Airport	Dourados":null,
"ERM	SSER	Erechim Airport	Erechim":null,
"FBA	SWOB	Fonte Boa Airport	Fonte Boa":null,
"FEN	SBFN	Fernando de Noronha Airport	Fernando Do Noronha":null,
"FLN	SBFL	Hercílio Luz International Airport	Florianopolis":null,
"FRC	SIMK	Franca Airport	Franca":null,
"GIG	SBGL	Rio Galeão – Tom Jobim International Airport	Rio De Janeiro":null,
"GPB	SBGU	Tancredo Thomas de Faria Airport	Guarapuava":null,
"GRU	SBGR	Guarulhos – Governador André Franco Montoro International Airport	Sao Paulo":null,
"GVR	SBGV	Coronel Altino Machado de Oliveira Airport	Governador Valadares":null,
"HUW	SWHT	Humaitá Airport	Humaita":null,
"IMP	SBIZ	Prefeito Renato Moreira Airport	Imperatriz":null,
"IPN	SBIP	Usiminas Airport	Ipatinga":null,
"ITB	SBIH	Itaituba Airport	Itaituba":null,
"IZA	SDZY	Zona da Mata Regional Airport	Juiz de Fora":null,
"JDF	SBJF	Francisco de Assis Airport	Juiz De Fora":null,
"JIA	SWJN	Juína Airport	Juina":null,
"JOI	SBJV	Lauro Carneiro de Loyola Airport	Joinville":null,
"JPR	SWJI	Ji-Paraná Airport	Ji-Paraná":null,
"JTC	SJTC	Bauru – Arealva Airport	Bauru":null,
"LAZ	SBLP	Bom Jesus da Lapa Airport	Bom Jesus Da Lapa":null,
"LDB	SBLO	Governador José Richa Airport	Londrina":null,
"LIP	SBLN	Lins Airport	Lins":null,
"MAB	SBMA	João Correa da Rocha Airport	Maraba":null,
"MBZ	SWMW	Maués Airport	Maues":null,
"MCZ	SBMO	Zumbi dos Palmares Airport	Maceio":null,
"MGF	SBMG	Regional de Maringá – Sílvio Nane Junior Airport	Maringa":null,
"MNX	SBMY	Manicoré Airport	Manicore":null,
"MQH	SBMC	Minaçu Airport	Minacu":null,
"MVS	SNMU	Mucuri Airport	Mucuri":null,
"NVP	SWNA	Novo Aripuanã Airport	Novo Aripuana":null,
"OAL	SSKW	Cacoal Airport	Cacoal":null,
"OLC	SDCG	Senadora Eunice Micheles Airport	Sao Paulo de Olivenca":null,
"ORX	SNOX	Oriximiná Airport	Oriximina":null,
"PCS	SNPC	Picos Airport	Picos":null,
"PFB	SBPF	Lauro Kurtz Airport	Passo Fundo":null,
"PLL	SBMN	Ponta Pelada Airport	Manaus":null,
"PMG	SBPP	Ponta Porã Airport	Ponta Pora":null,
"PNB	SBPN	Porto Nacional Airport	Porto Nacional":null,
"POA	SBPA	Salgado Filho Airport	Porto Alegre":null,
"POO	SBPC	Poços de Caldas – Embaixador Walther Moreira Salles Airport	Pocos De Caldas":null,
"PPY	SNZA	Pouso Alegre Airport	Pouso Alegre":null,
"QBX	SNOB	Sobral Airport	Sobral":null,
"QHP	SBTA	Base de Aviação de Taubaté Airport	Taubaté":null,
"QPS	SBYS	Campo Fontenelle Airport	Piracununga":null,
"RAO	SBRP	Leite Lopes Airport	Ribeirao Preto":null,
"RBR	SBRB	Plácido de Castro Airport	Rio Branco":null,
"REC	SBRF	Guararapes – Gilberto Freyre International Airport	Recife":null,
"ROO	SWRD	Maestro Marinho Franco Airport	Rondonopolis":null,
"SDU	SBRJ	Santos Dumont Airport	Rio De Janeiro":null,
"SJK	SBSJ	Professor Urbano Ernesto Stumpf Airport	Sao Jose Dos Campos":null,
"SJP	SBSR	Prof. Eribelto Manoel Reino State Airport	Sao Jose Do Rio Preto":null,
"SOD	SDCO	Sorocaba Airport	Sorocaba":null,
"SRA	SSZR	Santa Rosa Airport	Santa Rosa":null,
"SSZ	SBST	Base Aérea de Santos Airport	Santos":null,
"STU	SBSC	Santa Cruz Airport	Rio De Janeiro":null,
"SXO	SWFX	São Félix do Araguaia Airport	Sao Felix do Araguaia":null,
"TBT	SBTT	Tabatinga Airport	Tabatinga":null,
"TFL	SNTO	Juscelino Kubitscheck Airport	Teofilo Otoni":null,
"TJL	SSTL	Plínio Alarcom Airport	Tres Lagoas":null,
"TOW	SBTD	Toledo Airport	Toledo":null,
"UBA	SBUR	Mário de Almeida Franco Airport	Uberaba":null,
"UDI	SBUL	Ten. Cel. Aviador César Bombonato Airport	Uberlandia":null,
"UNA	SBTC	Hotel Transamérica Airport	Una":null,
"VAG	SBVG	Major Brigadeiro Trompowsky Airport	Varginha":null,
"VCP	SBKP	Viracopos International Airport	Campinas":null,
"VIX	SBVT	Eurico de Aguiar Salles Airport	Vitoria":null,
"XAP	SBCH	Serafin Enoss Bertaso Airport	Chapeco":null,
};